name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: Swatinem/rust-cache@v2.2.1

      - name: Create .env file and append secrets
        env:
          RSPOTIFY_CLIENT_ID: ${{ secrets.RSPOTIFY_CLIENT_ID }}
          RSPOTIFY_CLIENT_SECRET: ${{ secrets.RSPOTIFY_CLIENT_SECRET }}
          RSPOTIFY_REDIRECT_URI: ${{ secrets.RSPOTIFY_REDIRECT_URI }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_AUTH_URI: ${{ secrets.GOOGLE_AUTH_URI }}
          GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
        run: |
          echo "RSPOTIFY_CLIENT_ID=${RSPOTIFY_CLIENT_ID}" >> .env
          echo "RSPOTIFY_CLIENT_SECRET=${RSPOTIFY_CLIENT_SECRET}" >> .env
          echo "RSPOTIFY_REDIRECT_URI=${RSPOTIFY_REDIRECT_URI}" >> .env
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> .env
          echo "GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}" >> .env
          echo "GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}" >> .env

      - name: Build
        run: cargo build --verbose
