name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.2.1

    - name: Create .env file
      run: echo "YOUTUBE_API_KEY=" >> .env

    - name: Build
      run: cargo build --verbose
